/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PI_H_RPCGEN
#define _PI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PIPROG 0x39876543
#define CALCU_PIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCU_PI 1
extern  double * calcu_pi_1(void *, CLIENT *);
extern  double * calcu_pi_1_svc(void *, struct svc_req *);
extern int piprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCU_PI 1
extern  double * calcu_pi_1();
extern  double * calcu_pi_1_svc();
extern int piprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PI_H_RPCGEN */
