/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pi.h"

double *
calcu_pi_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  pi;

	double sum = 0;

 int i;

 int sign;

 for (i=1; i<10000000; i++ ){

sign = (i+1) % 2;

if ( sign == 0 )

 sign = 1;

else

 sign = -1;

sum += 1 / (2*(double)i -1) * (double)sign;

 } 

 pi = 4 * sum;

 return (&pi);
//	return &result;
}
