MYDATA SEGMENT
	BUFFER DB 100 DUP(0)
	PROMPT DB "PLEASE ENTER THE STRING",0DH,0AH,'$'
MYDATA ENDS

MYCODE SEGMENT
	ASSUME CS:MYCODE,DS:MYDATA
START: 
	mov dx, offset PROMPT
	mov ah, 09h
	int 21h	
	
	LEA BX, BUFFER
	MOV BYTE PTR [BX], 50H
	MOV AH, 0AH
	MOV DX, OFFSET BUFFER
	INT 21H
	
	MOV SI, OFFSET BUFFER
	MOV CL, [SI+1]
	MOV CH, 00

	LEA BX, BUFFER
	INC BX
		
PASS:	INC BX
	MOV AL,[BX]
	CMP AL, 'A'
	JC NOTHIN
	CMP AL,'Z'
	JNC NOTCAP
	ADD AL,20H
	JMP NOTHIN
NOTCAP:	CMP AL,'a'
	JC NOTHIN 
	CMP AL,'z'
	JNC NOTHIN
	SUB AL,20H

NOTHIN: MOV BYTE PTR [BX],AL
	LOOP PASS
	

	MOV SI, OFFSET BUFFER
	MOV CL, [SI+1]
	MOV CH, 00
	MOV AH, 40H
	MOV BX, 01	; FILE HANDLE, 01 FOR STDOUT
	MOV DX, SI
	ADD DX, 02
	INT 21H		

	MOV AH,4CH
	INT 21H

MYCODE ENDS
	END START